name: Node CI

on: push

jobs:
  test:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [22.14.x]

    steps:
    - uses: actions/checkout@master
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Node.js Test Suite
      run: |
        npm install
        npm test
